### PR TITLE
port Google Fonts 2016 glyph sets

### PR DESCRIPTION
**Pull request by felipesanches**
see also: https://github.com/googlefonts/fontbakery/issues/1189

### CODE REVIEW

**Comment by graphicore** [comment]
Do you think it's a good idea to copy all that code? It's at least bad for maintenance.

We could either try to create a separate package, at least for the Namelist code (libNamelist.py or so?) or you could consider using my inofficial [googleFontsTools](https://github.com/graphicore/googleFontsTools/) repository as a submodule, it extracts the `tools` directory of the google/fonts repository using `git filter-branch` . Though, if that thing is going to be used big time, we should automate updating it.

**Comment by felipesanches** [comment]
Yes, I'm aware of the issue of copying code and I knew this would be brought up. But since that code is not yet available as a python lib, and google/fonts repo is an absolutely giant beast, I decided to start of by copying the necessary code. I was sure we could later improve, as you suggested.

**Comment by felipesanches** [comment]
For that matter, there are actually two sets of things being copied:
* the file format parser code
* the glyphset files

**Comment by graphicore** [comment]
> google/fonts repo is an absolutely giant beast

So, do you think sth. like https://github.com/graphicore/googleFontsTools/ could be a solution to the beast problem? We could keep it updated using Travis.

**Comment by felipesanches** [comment]
Yes! That looks good!

**Comment by davelab6** [comment]
I could create a repo for the glyph sets, that seems to be the best thing?

**Comment by felipesanches** [comment]
> I could create a repo for the glyph sets, that seems to be the best thing?

Yes, That would be great, @davelab6 ! Both google/fonts and davelab6/pyfontaine should then set it up as a submodule repository and all updates to glyphsets then would be centralized on this new repo.

**Pull request merged**
